-- MEMBER TABLE --
DROP TABLE MEMBER CASCADE CONSTRAINT;
DROP SEQUENCE CODE_SEQ;

CREATE TABLE MEMBER 
(
  CODE CHAR(7 BYTE) NOT NULL 
, ID VARCHAR2(20 BYTE) NOT NULL 
, PW VARCHAR2(20 BYTE) NOT NULL 
, NAME VARCHAR2(30 BYTE) NOT NULL 
, NICKNAME VARCHAR2(30 BYTE) NOT NULL 
, GENDER CHAR(1 BYTE) NOT NULL 
, TEL VARCHAR2(16 BYTE) NOT NULL 
, EMAIL VARCHAR2(30 BYTE) NOT NULL 
, ADDR VARCHAR2(100 BYTE) 
, CTGRY VARCHAR2(25 BYTE) NOT NULL 
, ADMIN NUMBER(1, 0) NOT NULL 
, CONSTRAINT MEMBER_CODE_PK PRIMARY KEY (CODE)
, CONSTRAINT MEMBER_ID_UK UNIQUE(ID)
, CONSTRAINT MEMBER_NICKNAME_UK UNIQUE(NICKNAME)
, CONSTRAINT MEMBER_TEL_UK UNIQUE(TEL)
, CONSTRAINT MEMBER_EMAIL_UK UNIQUE(EMAIL)
);
CREATE SEQUENCE CODE_SEQ;

INSERT INTO MEMBER (CODE, ID, PW, NAME, NICKNAME, GENDER, TEL, EMAIL, ADDR, CTGRY, ADMIN) 
VALUES ('2020001', 'admin', '123', '나를밝혀조', '나를밝혀조', 'F', '010-0101-0100', 'admin@naver.com', '광주광역시', '관리자', '1');
INSERT INTO MEMBER (CODE, ID, PW, NAME, NICKNAME, GENDER, TEL, EMAIL, ADDR, CTGRY, ADMIN) 
VALUES ('2020002', 'a', 'a', '나를밝혀조1', '나를밝혀조1', 'F', '010-0101-0101', 'a@naver.com', '광주광역시', '공무원', '0');

-- TIMESET TABLE --
DROP TABLE TIMESET CASCADE CONSTRAINT;
DROP SEQUENCE SETNUM_SEQ;

CREATE TABLE TIMESET
(
  SETNUM NUMBER NOT NULL 
, NICKNAME VARCHAR2(30 BYTE) NOT NULL 
, STUDYMIN NUMBER(4, 0) NOT NULL 
, RESTMIN NUMBER(4, 0) NOT NULL 
, CONSTRAINT TIMESET_SETNUM_PK PRIMARY KEY (SETNUM)
, CONSTRAINT TIMESET_NICKNAME_FK FOREIGN KEY (NICKNAME) REFERENCES MEMBER (NICKNAME)
);
CREATE SEQUENCE SETNUM_SEQ;

-- STUDYSTATUS TABLE --
DROP TABLE STUDYSTATUS CASCADE CONSTRAINT;

CREATE TABLE STUDYSTATUS 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, STATUS NUMBER(1, 0) NOT NULL 
, CONSTRAINT STUDYSTATUS_ID_PK PRIMARY KEY (ID)
, CONSTRAINT STUDYSTATUS_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID)
);

-- USTIME TABLE --
DROP TABLE USTIME CASCADE CONSTRAINT;
DROP SEQUENCE UNUM_SEQ;

CREATE TABLE USTIME 
(
  UNUM NUMBER NOT NULL 
, NICKNAME VARCHAR2(30 BYTE) NOT NULL
, USTART DATE NOT NULL
, UEND DATE 
, USEC NUMBER(5, 0) 
, REALSTUDYUSEC NUMBER(5, 0) 
, REALRESTUSEC NUMBER(5, 0) 
, CONSTRAINT USTIME_UNUM_PK PRIMARY KEY (UNUM)
, CONSTRAINT USTIME_NICKNAME_FK FOREIGN KEY (NICKNAME) REFERENCES MEMBER (NICKNAME)
);
CREATE SEQUENCE UNUM_SEQ;

-- BOARD TABLE --
DROP TABLE BOARD CASCADE CONSTRAINT;
DROP SEQUENCE BNUM_SEQ;

CREATE TABLE BOARD 
(
  BNUM NUMBER NOT NULL 
, BPW VARCHAR2(20 BYTE) NOT NULL
, NICKNAME VARCHAR2(30 BYTE) NOT NULL 
, BEMAIL VARCHAR2(30 BYTE) 
, TITLE VARCHAR2(50 BYTE) NOT NULL 
, CONTENT VARCHAR2(1000 BYTE) 
, WRITEDATE DATE NOT NULL 
, A_CONTENT VARCHAR2(1000 BYTE) 
, A_CHECK CHAR(1 BYTE) NOT NULL
, CONSTRAINT BOARD_BNUM_PK PRIMARY KEY (BNUM)
, CONSTRAINT BOARD_NICKNAME_FK FOREIGN KEY (NICKNAME) REFERENCES MEMBER (NICKNAME)
);
CREATE SEQUENCE BNUM_SEQ;

-- DSTIME VIEW --
DROP TABLE DSTIME CASCADE CONSTRAINT;

CREATE OR REPLACE VIEW DSTIME
AS
SELECT NICKNAME, TO_CHAR(USTART, 'YYYY-MM-DD') AS DDAY, SUM(REALSTUDYUSEC) AS DSEC, SUM(REALRESTUSEC) AS RESTDSEC
FROM USTIME
GROUP BY NICKNAME, TO_CHAR(USTART, 'YYYY-MM-DD')
ORDER BY DDAY;

-- WSTIME VIEW --
DROP TABLE WSTIME CASCADE CONSTRAINT;

CREATE OR REPLACE VIEW WSTIME
AS
SELECT NICKNAME, TO_CHAR(NEXT_DAY(DDAY,'일요일') - 7, 'YYYY-MM-DD') AS SWEEK, TO_CHAR(NEXT_DAY(DDAY,'일요일') - 1, 'YYYY-MM-DD') AS EWEEK, SUM(DSEC) AS WSEC, SUM(RESTDSEC) AS RESTWSEC
 FROM DSTIME
GROUP BY NICKNAME, NEXT_DAY(DDAY,'일요일'),NEXT_DAY(DDAY, '일요일')-7;

-- MSTIME VIEW --
DROP TABLE MSTIME CASCADE CONSTRAINT;

CREATE OR REPLACE VIEW MSTIME
AS
SELECT NICKNAME, SUBSTR(DDAY, 0, 7) AS MONTH, TO_CHAR(LAST_DAY(DDAY), 'DD') AS LASTDAY, SUM(DSEC) AS MSEC, SUM(RESTDSEC) AS RESTMSEC
FROM DSTIME
GROUP BY NICKNAME, SUBSTR(DDAY, 0, 7), LAST_DAY(DDAY);
